In [62]:
import pandas as pd

In [63]:
data = pd.read_csv("customer_orders.csv")
df = pd.DataFrame(data)

In [64]:
df

    OrderID    CustomerName     Product  Quantity  PricePerUnit
0       101        John Doe      Laptop       1.0       1200.50
1       102      Jane Smith       Phone       2.0        699.99
2       103             NaN          TV       1.0      45000.00
3       104      Mike Brown      Tablet       1.0      20000.00
4       105   Alice Johnson     Speaker       3.0       1500.00
5       105   Alice Johnson     Speaker       3.0       1500.00
6       106             NaN  Smartwatch      -1.0       2999.00
7       107     David Clark  Headphones       2.0       5000.00
8       108       Eve Black     Monitor       1.0           NaN
9       109     Frank White    Keyboard       1.0        200.00
10      110     Emily Green       Mouse       NaN         50.00
11      111         Tom Lee  Smartwatch       2.0       2500.00
12      112     Nancy Moore   Earphones       1.0        299.99
13      113       John Snow      Laptop       3.0      75000.00
14      114      Emma Stone       Phone       1.0        999.99
15      115    Daniel Craig      Tablet       4.0           NaN
16      116   Sophia Turner     Speaker       2.0       1999.00
17      117   Michael Scott         NaN       1.0       3500.00
18      118     Jim Halpert  Headphones       2.0       1500.00
19      119      Pam Beesly    Keyboard       3.0       1200.00
20      120  Dwight Schrute       Mouse       2.0        399.99

In [65]:
df.isnull().sum()

OrderID         0
CustomerName    2
Product         1
Quantity        1
PricePerUnit    2
dtype: int64

In [66]:
#1a
df['CustomerName'] = df['CustomerName'].fillna(value = "Unknown")

In [67]:
#1b
df['Product'] = df['Product'].fillna(value = "Unknown Product")

In [68]:
#1c
df.dropna(subset=['Quantity'], inplace=True)

In [70]:
#1d
df['PricePerUnit'] = df['PricePerUnit'].fillna(value = df['PricePerUnit'].mean())

In [71]:
#2a
df['Quantity'] = df['Quantity'].abs()

In [77]:
#3a
df = df.drop_duplicates()

In [80]:
#4a
df['Quantity'] = df['Quantity'].astype('Int64')

/var/folders/jv/5vrg9pr10hq1ywzjk97sn5fw0000gn/T/ipykernel_8028/3662267151.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Quantity'] = df['Quantity'].astype('Int64')

In [81]:
#5a
df['TotalPrice'] = df['Quantity'] * df['PricePerUnit']

/var/folders/jv/5vrg9pr10hq1ywzjk97sn5fw0000gn/T/ipykernel_8028/3255554201.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TotalPrice'] = df['Quantity'] * df['PricePerUnit']

In [82]:
df

,OrderID,CustomerName,Product,Quantity,PricePerUnit,TotalPrice
0,101,John Doe,Laptop,1,1200.500000,1200.5
1,102,Jane Smith,Phone,2,699.990000,1399.98
2,103,Unknown,TV,1,45000.000000,45000.0
3,104,Mike Brown,Tablet,1,20000.000000,20000.0
4,105,Alice Johnson,Speaker,3,1500.000000,4500.0
6,106,Unknown,Smartwatch,1,2999.000000,2999.0
7,107,David Clark,Headphones,2,5000.000000,10000.0
8,108,Eve Black,Monitor,1,9194.358889,9194.358889
9,109,Frank White,Keyboard,1,200.000000,200.0
11,111,Tom Lee,Smartwatch,2,2500.000000,5000.0
12,112,Nancy Moore,Earphones,1,299.990000,299.99
13,113,John Snow,Laptop,3,75000.000000,225000.0
14,114,Emma Stone,Phone,1,999.990000,999.99
15,115,Daniel Craig,Tablet,4,9194.358889,36777.435556
16,116,Sophia Turner,Speaker,2,1999.000000,3998.0
17,117,Michael Scott,Unknown Product,1,3500.000000,3500.0
18,118,Jim Halpert,Headphones,2,1500.000000,3000.0
19,119,Pam Beesly,Keyboard,3,1200.000000,3600.0
20,120,Dwight Schrute,Mouse,2,399.990000,799.98